name: Daily

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.COMMIT_KEY }}
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          npm version $(date +%Y.%m.%d)
          git push
          git push --tags
