name: Daily

on:
  schedule:
    - cron: "0 0 * * *"
  watch:
    types: [started]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - run: |
          git config user.name "anuoua"
          git config user.email "anuoua@gmail.com"
          npm version $(date +%Y.%m.%d)
          git push
          git push --tags
